name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug","issue"]
assignees:
  - Pilot1782
body:
  - type: markdown
    attributes:
      value: |
        Before filling this out, check the [Installation guide](https://github.com/Pilot1782/bad_copenheimer/wiki/Installation-(New-Bot)) and/or check out the [troubleshooting page](https://github.com/Pilot1782/bad_copenheimer/wiki/Troubleshooting).
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: OS
    attributes:
      label: Operating Sys
      description: What os are you using?
      options:
        - Linux
        - Windows
    validations:
      required: true
  - type: dropdown
    id: Branch
    attributes:
      label: Branch
      description: Which branch are you using?
      options:
        - main
        - dev-builds
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: true
